######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 17 18:26:57 2011
######################################################################

TEMPLATE = app
TARGET = kvmbox
DEPENDPATH += .
INCLUDEPATH += .

# Input

HEADERS += kvmbox.h
SOURCES += gui.cpp kvmbox.c pci.c smbus.c

nogui {
    SOURCES = main.c kvmbox.c pci.c smbus.c
}
