######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 17 18:26:57 2011
######################################################################

TEMPLATE = app
TARGET = kvmbox
DEPENDPATH += .
INCLUDEPATH += .

# Input

HEADERS += kvmbox.h kvmbox.hh
SOURCES += gui.cpp kvmbox.cpp pci.c smbus.c

